# This workflow will release a .NET project
# For more information see: https://docs.github.com/en/actions/publishing-packages/about-packaging-with-github-actions

name: Wyrm.Math Release

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Restore dependencies
      run: dotnet restore src/Wyrm.Math/Wyrm.Math.csproj
    - name: Pack
      run: dotnet pack src/Wyrm.Math/Wyrm.Math.csproj --no-restore --configuration Release --output "NugetPackage"
    - name: Push package to nuget
      run: dotnet nuget push "NugetPackage/*.nupkg" -k ${{secrets.NUGET_TOKEN}} -s https://api.nuget.org/v3/index.json
